# Generated by Django 4.0.3 on 2022-05-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0002_category_question_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='quizmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('op1', models.CharField(max_length=1000)),
                ('op2', models.CharField(max_length=1000)),
                ('op3', models.CharField(max_length=1000)),
                ('op4', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
