# Generated by Django 4.0.3 on 2022-05-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_quizmodel_remove_question_categories_delete_answers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'file_model',
            },
        ),
    ]
